"""empty message

<<<<<<< HEAD:migrations/versions/cd8e7cc84fe0_.py
Revision ID: cd8e7cc84fe0
Revises: 
Create Date: 2020-05-16 09:10:56.556190
=======
Revision ID: 16542549d994
Revises: 
Create Date: 2020-05-11 22:29:52.173821
>>>>>>> bf47d7d176457436215df93d011b36b7d5b47668:migrations/versions/16542549d994_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<< HEAD:migrations/versions/cd8e7cc84fe0_.py
revision = 'cd8e7cc84fe0'
=======
revision = '16542549d994'
>>>>>>> bf47d7d176457436215df93d011b36b7d5b47668:migrations/versions/16542549d994_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=80), nullable=True),
    sa.Column('bio', sa.String(length=250), nullable=True),
    sa.Column('proPhoto', sa.String(length=200), nullable=True),
    sa.Column('joined_on', sa.DateTime(), nullable=True),
<<<<<<< HEAD:migrations/versions/cd8e7cc84fe0_.py
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
=======
    sa.PrimaryKeyConstraint('id')
>>>>>>> bf47d7d176457436215df93d011b36b7d5b47668:migrations/versions/16542549d994_.py
    )
    op.create_table('Follow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('photo', sa.String(length=80), nullable=True),
    sa.Column('caption', sa.String(length=250), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['Post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Like')
    op.drop_table('Post')
    op.drop_table('Follow')
    op.drop_table('User')
    # ### end Alembic commands ###
