"""empty message

Revision ID: 24f0c0b7bc24
Revises: e96bae7f3814
Create Date: 2020-05-16 05:53:10.071934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24f0c0b7bc24'
down_revision = 'e96bae7f3814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('User', 'first_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('User', 'last_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.create_unique_constraint(None, 'User', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='unique')
    op.alter_column('User', 'last_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('User', 'first_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('User', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
