"""empty message

Revision ID: 85dc9ce29e6f
Revises: 24f0c0b7bc24
Create Date: 2020-05-16 05:59:33.066216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85dc9ce29e6f'
down_revision = '24f0c0b7bc24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('password', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'password')
    # ### end Alembic commands ###
