"""empty message

Revision ID: e96bae7f3814
Revises: 80e7edc14ef3
Create Date: 2020-05-14 14:04:40.788843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e96bae7f3814'
down_revision = '80e7edc14ef3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('username', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'username')
    # ### end Alembic commands ###
